### ISSUE TITLE
🔥 login page

### ISSUE THREAD

**Issue by janzenfaidiban** [sagufoundation/sagu-database-laravel#10]
- [x] tab / title: tambahkan judul aplikasi "SF Connect"
- [x] hapus : checkbox ingat saya dia tas tombol Masuk
- [x] tambahkan icon "sign in" di tombol "Masuk"
- [x] tambah gambar favicon dan app title di halaman login

**Comment by samuelbosawer** [comment]
[Done]  tab / title: tambahkan judul aplikasi "SF Connect"
[ Done]  hapus : checkbox ingat saya dia tas tombol Masuk
[Done]  tambahkan icon "sign in" di tombol "Masuk"

![Image](https://github.com/sagufoundation/sagu-database-laravel/assets/60697963/8e2e012c-1f65-4d4f-a42a-f3e1b2d9df33)
